{
 "title": "Custom Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Taxa de Requisições por Minuto (por Endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"ecommerce\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições por Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"ecommerce\"}) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência das Requisições",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"ecommerce\"}[1m]) \n/ \nrate(http_server_requests_seconds_count{application=\"ecommerce\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Erros (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"ecommerce\",status=\"500\"}[1m])) \n/ \nsum(rate(http_server_requests_seconds_count{application=\"ecommerce\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões Ativas do Banco",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"ecommerce\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}