apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  database-url: jdbc:postgresql://postgres:5432/ecommerce
  database-username: postgres
  database-password: postgres 