global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ecommerce-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: ecommerce 